name: turskyi
description: Personal web page.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
homepage: https://turskyi.com
version: 1.0.2

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  dio: ^5.9.0
  email_validator: ^3.0.0
  envied: ^1.3.2
  envied_generator: ^1.3.2
  flutter:
    sdk: flutter

  # display svg images
  flutter_svg: ^2.2.3

  #  localization
  flutter_translate:
    git:
      url: https://github.com/Javernaver/flutter_translate.git
      ref: master

  mockito: ^5.6.1

  #  Add ChangeNotifierProvider and Consumer for implementing the MVP structural
  #  design pattern.
  provider: ^6.1.5+1

  resend: ^1.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  # Tried ^2.6.0, and it does not compile.
  build_runner: ^2.10.4
  flutter_test:
    sdk: flutter

  # The set of rules follows the Effective Dart: Style Guide.
  lint: ^2.8.0

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons' font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # assets of the application
  assets:
    #    strings
    - assets/i18n/
    #    picture files
    - assets/images/
    - assets/images/feature_graphics/


